version: '3.8'

services:
  backend:
    image: tald-unia-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_NODES=redis:6379
      - REDIS_TLS=true
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - NODE_OPTIONS=--max-old-space-size=4096 --optimize-for-size
      - UV_THREADPOOL_SIZE=64
      - NODE_CLUSTER_WORKERS=auto
      - SECURITY_HEADERS_ENABLED=true
      - SECURITY_HEADERS_HSTS_ENABLED=true
      - SECURITY_HEADERS_CSP_ENABLED=true
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules:ro
      - dist:/app/dist:ro
      - tmp_data:/tmp/tald
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    user: node
    networks:
      - tald-network
    secrets:
      - redis_password

  redis:
    image: redis:7.2-alpine
    command: redis-server --requirepass $${REDIS_PASSWORD} --maxmemory 2gb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - tald-network
    secrets:
      - redis_password

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - prometheus_data:/prometheus
      - type: config
        source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - tald-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  grafana:
    image: grafana/grafana:9.5.2
    volumes:
      - grafana_data:/var/lib/grafana
      - type: config
        source: grafana_provisioning
        target: /etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
    ports:
      - "3001:3000"
    networks:
      - tald-network
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    secrets:
      - grafana_admin_password

volumes:
  node_modules:
    driver_opts:
      type: none
      device: /app/node_modules
      o: bind,ro
  dist:
    driver_opts:
      type: none
      device: /app/dist
      o: bind,ro
  redis_data:
    driver_opts:
      type: none
      device: /data/redis
      o: bind
  prometheus_data:
    driver_opts:
      type: none
      device: /data/prometheus
      o: bind
  grafana_data:
    driver_opts:
      type: none
      device: /data/grafana
      o: bind
  tmp_data:
    driver: local

networks:
  tald-network:
    driver: overlay
    attachable: true
    internal: true
    driver_opts:
      encrypted: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

secrets:
  redis_password:
    file: ./secrets/redis_password.txt
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt

configs:
  prometheus_config:
    file: ./infrastructure/monitoring/prometheus/prometheus.yml
  grafana_provisioning:
    file: ./infrastructure/monitoring/grafana/provisioning/dashboards