apiVersion: v1
kind: Service
metadata:
  name: tald-web-service
  namespace: tald-unia
  labels:
    app: tald-web
    component: frontend
    tier: web
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: tald-web
    component: frontend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  publishNotReadyAddresses: false
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"