version: '3.8'

services:
  # Development service configuration
  web_dev:
    image: node:18-alpine
    container_name: tald_web_dev
    environment:
      - NODE_ENV=development
      - VITE_APP_ENV=development
      - VITE_DEBUG=true
      - VITE_WEBRTC_DEBUG=true
      - VITE_PERFORMANCE_MONITORING=true
    env_file: .env.development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - ./src:/app/src:delegated
    working_dir: /app
    command: npm run dev
    networks:
      - tald_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    pids_limit: 100
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Production service configuration
  web_prod:
    image: nginx:1.24-alpine
    container_name: tald_web_prod
    environment:
      - NODE_ENV=production
      - VITE_APP_ENV=production
      - VITE_DEBUG=false
      - VITE_PERFORMANCE_MONITORING=true
    env_file: .env.production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ssl_certs:/etc/nginx/ssl:ro
    networks:
      - tald_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    ulimits:
      nofile:
        soft: 2048
        hard: 4096
    pids_limit: 50
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  node_modules:
    name: tald_node_modules
  ssl_certs:
    name: tald_ssl_certs
    driver: local
    driver_opts:
      type: none
      device: /etc/ssl/tald
      o: bind

networks:
  tald_network:
    driver: bridge
    enable_ipv6: true
    internal: true
    attachable: false
    driver_opts:
      com.docker.network.bridge.name: tald_net
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
        - subnet: 2001:db8::/64