# UNIA OS Boot Configuration

[system]
name = "UNIA OS"
version = "0.1.0"
description = "Open Source AI Gaming Operating System"

[display]
resolution = "1920x1080"
color_depth = 32
refresh_rate = 60
fullscreen = true

[boot]
splash_screen = true
splash_duration = 3  # seconds
verbose_boot = false
recovery_mode = false

[hardware]
default_profile = "standard_console"
enable_acceleration = true
enable_virtualization = true

[network]
enable_mesh = true
max_connections = 64
discovery_port = 7777

[ai]
enable_ai_subsystem = true
behavior_tree_complexity = "high"
procedural_generation = true

[game]
enable_game_engine = true
physics_engine = "standard"
render_engine = "advanced"

[debug]
enable_logging = true
log_level = "info"  # debug, info, warn, error
enable_profiling = false
