name: Backend CI

on:
  push:
    branches: 
      - main
      - develop
    paths:
      - src/backend/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/backend/**

env:
  NODE_VERSION: '18.x'
  WORKING_DIRECTORY: 'src/backend'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci

      - name: Lint
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run lint

      - name: Type check
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build --noEmit

      - name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run test:coverage
        env:
          CI: true

  security:
    name: Security Scan
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          queries: security-extended

      - name: Analyze
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"
          upload-database: true